"""make bank_account_id nullable for oauth users

Revision ID: a40936c66554
Revises: f0bae97fb421
Create Date: 2026-09-18 11:32:53.206629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40936c66554'
down_revision: Union[str, Sequence[str], None] = 'f0bae97fb421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bank_account_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bank_account_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
